hash-format = "sha256"

[[files]]
file = "mods/advanced-peripherals.pw.toml"
metafile = true

[[files]]
file = "mods/ae2-things-forge.pw.toml"
metafile = true

[[files]]
file = "mods/ae2.pw.toml"
metafile = true

[[files]]
file = "mods/akashic-tome.pw.toml"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
metafile = true

[[files]]
file = "mods/applied-energistics-2.pw.toml"
metafile = true

[[files]]
file = "mods/applied-mekanistics.pw.toml"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/ars-nouveau.pw.toml"
metafile = true

[[files]]
file = "mods/artifacts.pw.toml"
metafile = true

[[files]]
file = "mods/autoreglib.pw.toml"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
metafile = true

[[files]]
file = "mods/biomesyougo.pw.toml"
metafile = true

[[files]]
file = "mods/blood-magic.pw.toml"
metafile = true

[[files]]
file = "mods/bookshelf.pw.toml"
metafile = true

[[files]]
file = "mods/botania.pw.toml"
metafile = true

[[files]]
file = "mods/building-gadgets.pw.toml"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
metafile = true

[[files]]
file = "mods/chance-cubes.pw.toml"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/codechicken-lib-1-8.pw.toml"
metafile = true

[[files]]
file = "mods/cofh-core.pw.toml"
metafile = true

[[files]]
file = "mods/common-capabilities.pw.toml"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
metafile = true

[[files]]
file = "mods/cosmetic-armor-reworked.pw.toml"
metafile = true

[[files]]
file = "mods/crafting-tweaks.pw.toml"
metafile = true

[[files]]
file = "mods/create-enchantment-industry.pw.toml"
metafile = true

[[files]]
file = "mods/create-goggles.pw.toml"
metafile = true

[[files]]
file = "mods/create-steam-n-rails.pw.toml"
metafile = true

[[files]]
file = "mods/create.pw.toml"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
metafile = true

[[files]]
file = "mods/ctm.pw.toml"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
metafile = true

[[files]]
file = "mods/cyclops-core.pw.toml"
metafile = true

[[files]]
file = "mods/dark-mode-everywhere.pw.toml"
metafile = true

[[files]]
file = "mods/dark-utilities.pw.toml"
metafile = true

[[files]]
file = "mods/dungeon-crawl.pw.toml"
metafile = true

[[files]]
file = "mods/dungeons-plus.pw.toml"
metafile = true

[[files]]
file = "mods/ender-storage-1-8.pw.toml"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
metafile = true

[[files]]
file = "mods/expandability.pw.toml"
metafile = true

[[files]]
file = "mods/experience-obelisk.pw.toml"
metafile = true

[[files]]
file = "mods/extreme-sound-muffler.pw.toml"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/findme.pw.toml"
metafile = true

[[files]]
file = "mods/flux-networks.pw.toml"
metafile = true

[[files]]
file = "mods/flywheel.pw.toml"
metafile = true

[[files]]
file = "mods/functional-storage.pw.toml"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
metafile = true

[[files]]
file = "mods/gravestone-mod.pw.toml"
metafile = true

[[files]]
file = "mods/industrial-foregoing.pw.toml"
metafile = true

[[files]]
file = "mods/integrated-dynamics.pw.toml"
metafile = true

[[files]]
file = "mods/integrated-tunnels.pw.toml"
metafile = true

[[files]]
file = "mods/inventory-essentials.pw.toml"
metafile = true

[[files]]
file = "mods/inventory-sorter.pw.toml"
metafile = true

[[files]]
file = "mods/iron-chests.pw.toml"
metafile = true

[[files]]
file = "mods/jade-addons.pw.toml"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
metafile = true

[[files]]
file = "mods/journeymap-integration.pw.toml"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
metafile = true

[[files]]
file = "mods/lazierae2.pw.toml"
metafile = true

[[files]]
file = "mods/mantle.pw.toml"
metafile = true

[[files]]
file = "mods/mcjtylib.pw.toml"
metafile = true

[[files]]
file = "mods/mekanism-additions.pw.toml"
metafile = true

[[files]]
file = "mods/mekanism-generators.pw.toml"
metafile = true

[[files]]
file = "mods/mekanism-tools.pw.toml"
metafile = true

[[files]]
file = "mods/mekanism.pw.toml"
metafile = true

[[files]]
file = "mods/mining-gadgets.pw.toml"
metafile = true

[[files]]
file = "mods/modular-routers.pw.toml"
metafile = true

[[files]]
file = "mods/morph-o-tool.pw.toml"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
metafile = true

[[files]]
file = "mods/open-parties-and-claims.pw.toml"
metafile = true

[[files]]
file = "mods/ore-excavation.pw.toml"
metafile = true

[[files]]
file = "mods/overloaded-armor-bar.pw.toml"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
metafile = true

[[files]]
file = "mods/pig-pen-cipher.pw.toml"
metafile = true

[[files]]
file = "mods/powah.pw.toml"
metafile = true

[[files]]
file = "mods/quark.pw.toml"
metafile = true

[[files]]
file = "mods/roughly-enough-items-hacks.pw.toml"
metafile = true

[[files]]
file = "mods/roughly-enough-items.pw.toml"
metafile = true

[[files]]
file = "mods/roughly-enough-resources.pw.toml"
metafile = true

[[files]]
file = "mods/runelic.pw.toml"
metafile = true

[[files]]
file = "mods/simply-backpacks.pw.toml"
metafile = true

[[files]]
file = "mods/smooth-boot-reloaded.pw.toml"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
metafile = true

[[files]]
file = "mods/starlight-forge.pw.toml"
metafile = true

[[files]]
file = "mods/structure-gel-api.pw.toml"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.pw.toml"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
metafile = true

[[files]]
file = "mods/thermal-expansion.pw.toml"
metafile = true

[[files]]
file = "mods/thermal-foundation.pw.toml"
metafile = true

[[files]]
file = "mods/thermal-integration.pw.toml"
metafile = true

[[files]]
file = "mods/time-in-a-bottle-standalone.pw.toml"
metafile = true

[[files]]
file = "mods/tinkers-construct.pw.toml"
metafile = true

[[files]]
file = "mods/titanium.pw.toml"
metafile = true

[[files]]
file = "mods/torchmaster.pw.toml"
metafile = true

[[files]]
file = "mods/trash-cans.pw.toml"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
metafile = true
