name = "Hack Pack v4"
author = "The Hack Club Community"
version = "dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f219973ac98f8d24784e5475cb9bcbce7cd803a30415fb630e0f9b509f09efa"

[versions]
forge = "45.0.0"
minecraft = "1.19.4"
